In [1]:
#import pandas as pd
import numpy as np

In [2]:
l = [0,1,2,3,4] # list
arr = np.array(l) # transforming list to array
type(l),type(arr), arr.dtype #type for arr / type for elements of arr

(list, numpy.ndarray, dtype('int32'))

In [3]:
l = [[0,1],[2,3]]
arr = np.array(l)
type(l),type(arr),arr

(list,
 numpy.ndarray,
 array([[0, 1],
        [2, 3]]))

In [4]:
arr.shape # array size
arr.ndim # number of dimensions(axes) array (columns and rows, 2-dimension array)

2

In [15]:
np.zeros(5),np.ones([2,2]),np.empty([2,3,4])

(array([0., 0., 0., 0., 0.]),
 array([[1., 1.],
        [1., 1.]]),
 array([[[6.02414664e-282, 0.00000000e+000, 2.27582644e-317,
          0.00000000e+000],
         [9.81961191e-308, 1.16202259e-301, 1.84767285e-300,
          9.81909452e-306],
         [0.00000000e+000, 6.37802999e-314, 1.55916087e-300,
          1.47916816e-299]],
 
        [[1.55916091e-300, 9.82022311e-308, 3.07690995e-312,
          2.47929914e-307],
         [2.29562475e-282, 4.45619116e-313, 1.58101007e-322,
          0.00000000e+000],
         [4.94065646e-324, 4.24399158e-314, 1.71883264e-312,
          2.47919050e-307]]]))

In [5]:
arr2 = np.arange(10)
arr2,type(arr2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [6]:
np.ones_like(arr2),np.zeros_like(arr2),np.empty_like(arr2)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([4606108, 4606108,    -111,    -111,    -111,    -111,    -111,
           -111,    -111,    -111]))

In [7]:
np.eye(3),np.identity(3)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [34]:
e = np.empty_like(arr2)
e.dtype
arr3 = e.astype(np.float64) # transforming type of elements
arr3.dtype,arr3

(dtype('float64'),
 array([       0.,        0.,        0.,  3206936.,        0., 10208824.,
               0.,        0., 67108865.,  4606244.]))

In [40]:
arr,arr - arr,arr*arr,arr**2,arr*5  # array operations

(array([[0, 1],
        [2, 3]]),
 array([[0, 0],
        [0, 0]]),
 array([[0, 1],
        [4, 9]]),
 array([[0, 1],
        [4, 9]]),
 array([[ 0,  5],
        [10, 15]]))

In [63]:
# index and cut
arr1 = np.array([0,1,2,3,4,5]) # for 1-dimensional array
arr1[3], arr1[2:4]

(3, array([2, 3]))

In [64]:
arr1[2:4] = 12

In [65]:
arr1

array([ 0,  1, 12, 12,  4,  5])

In [71]:
arr,arr[0][1],arr[0,1] # [rows][columns] or [rows,columns] for 2-dimensional array

(array([[0, 1],
        [2, 3]]),
 1,
 1)

In [8]:
arr[0]

array([0, 1])

In [11]:
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2d,arr2d[:2,1:],arr2d[:1] # number to the left is included, number to the right isn't

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1, 2],
        [4, 5]]),
 array([[0, 1, 2]]))

### Boolean indexing

In [19]:
rand = np.random.randn(5)
a = np.arange(5)
a == rand, a == 1, a != 1,rand[a != 1],rand[~(a == 1)]

(array([False, False, False, False, False]),
 array([False,  True, False, False, False]),
 array([ True, False,  True,  True,  True]),
 array([-1.10412775,  0.87310607, -0.14388842, -1.04358411]),
 array([-1.10412775,  0.87310607, -0.14388842, -1.04358411]))

In [22]:
a[(a != 1) & (a!= 0)], a[(a == 1) | (a == 0)]

(array([2, 3, 4]), array([0, 1]))

### fancy indexing

In [47]:
a = np.empty([7,4])
for i in range(7):
    a[i] = i
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [53]:
a[[2,3,0,1,4,5,6]] #  row's permutation

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [51]:
a[-1],a[-1,-1] # negative indexes

(array([6., 6., 6., 6.]), 6.0)

### reshape

In [63]:
b = np.arange(24)
b = b.reshape((4,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [86]:
b[[0,1,2,3],[1,2,3,4]]

array([ 1,  8, 15, 22])

In [84]:
b[[0,1,2,3]][:,[1,2,3,4]] # fancy indexing
b[np.ix_([0,1,2,3],[1,2,3,4])]

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])

### транспонирование

In [90]:
c = np.arange(6).reshape((2,3))
c,c.T

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 3],
        [1, 4],
        [2, 5]]))

In [91]:
np.dot(c.T,c) # matrix multiplication

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

In [ ]:
arr.swapaxes # (для транспонирования многомерных матриц)